class AgentEnum:
    ADD_MAP = "new"  # "Add a new map to User maps"
    ADD_SCHEDULE = "ADD_SCHEDULE"  # "Add a new Schedule to map that is open"
    SHOW_ALL_THREADS = "SHOW_ALL_THREADS"
    LIST_MAPS = "list"
    LIST_SCHEDULES = "listsched"  # "Lists available schedule ids on the current selected map"
    LIST_STOPS = "list_stops"  # "Lists all stops on the choosen map"
    LIST_ROUTES = "list_routes"
    OPEN_MAP = "open"
    CLOSE_MAP = "close"
    EDIT_SCHEDULE = "edit"
    ADD_ROUTE = "new_route"  # "Add new route to the given schedule (Usage : new_route <schedule_id> <stop_number> <stop_id1> ...)"
